"""
Tests for src/voc_to_yolo.py against hand-computed known-correct output —
not just "does it run," per this project's standing rule that numeric/format
transformations get verified against a manually worked example, because a
previous VOC->YOLO converter in this project had a real escaped-newline bug
that only showed up under that kind of check.

Hand-computed fixture (all worked by hand below, not generated by the code
under test):

  Image: 1000 x 500 px.

  Object 1 — "Wrench", bbox (xmin=100, ymin=50, xmax=300, ymax=150):
    x_center = (100+300)/2 / 1000 = 200/1000  = 0.2
    y_center = (50+150)/2  / 500  = 100/500   = 0.2
    w        = (300-100)   / 1000 = 200/1000  = 0.2
    h        = (150-50)    / 500  = 100/500   = 0.2
    class_id for "Wrench" in CLASS_NAMES (index 0) => "0 0.2 0.2 0.2 0.2"

  Object 2 — "NotAFODClass" (not in CLASS_NAMES): must be skipped and
    counted, not silently dropped.

  Object 3 — "SodaCan", bbox that overhangs the frame
    (xmin=-10, ymin=10, xmax=1005, ymax=490), which the converter must
    clamp to (0, 10, 1000, 490) before normalizing:
    x_center = (0+1000)/2  / 1000 = 500/1000  = 0.5
    y_center = (10+490)/2  / 500  = 250/500   = 0.5
    w        = (1000-0)    / 1000 = 1000/1000 = 1.0
    h        = (490-10)    / 500  = 480/500   = 0.96
    class_id for "SodaCan" in CLASS_NAMES (index 3) => "3 0.5 0.5 1.0 0.96"
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from voc_to_yolo import (  # noqa: E402
    convert_directory,
    convert_original_format_distribution,
    list_all_classes,
    parse_voc_xml,
    voc_box_to_yolo_line,
)

CLASS_NAMES = ["Wrench", "Hammer", "Screwdriver", "SodaCan", "Wood"]
FASTENER_CLASS_NAMES = ["Bolt", "Nut", "Washer", "BoltWasher", "BoltNutSet", "Screw", "Nail"]

VALID_XML = """<annotation>
  <folder>fod-a</folder>
  <filename>sample1.jpg</filename>
  <size>
    <width>1000</width>
    <height>500</height>
    <depth>3</depth>
  </size>
  <object>
    <name>Wrench</name>
    <bndbox>
      <xmin>100</xmin>
      <ymin>50</ymin>
      <xmax>300</xmax>
      <ymax>150</ymax>
    </bndbox>
  </object>
  <object>
    <name>NotAFODClass</name>
    <bndbox>
      <xmin>10</xmin>
      <ymin>10</ymin>
      <xmax>20</xmax>
      <ymax>20</ymax>
    </bndbox>
  </object>
  <object>
    <name>SodaCan</name>
    <bndbox>
      <xmin>-10</xmin>
      <ymin>10</ymin>
      <xmax>1005</xmax>
      <ymax>490</ymax>
    </bndbox>
  </object>
</annotation>
"""

MALFORMED_XML = "<annotation><size><width>100</width><height>100</height>"  # truncated, invalid XML

NO_KNOWN_OBJECTS_XML = """<annotation>
  <size><width>200</width><height>200</height><depth>3</depth></size>
  <object>
    <name>NotAFODClass</name>
    <bndbox><xmin>1</xmin><ymin>1</ymin><xmax>5</xmax><ymax>5</ymax></bndbox>
  </object>
</annotation>
"""


def test_voc_box_to_yolo_line_matches_hand_computed_values():
    # Object 1, hand-computed above.
    line = voc_box_to_yolo_line(0, 100, 50, 300, 150, img_w=1000, img_h=500)
    cls, xc, yc, w, h = line.split()
    assert cls == "0"
    assert abs(float(xc) - 0.2) < 1e-6
    assert abs(float(yc) - 0.2) < 1e-6
    assert abs(float(w) - 0.2) < 1e-6
    assert abs(float(h) - 0.2) < 1e-6


def test_parse_voc_xml_reads_size_and_objects():
    import tempfile

    with tempfile.TemporaryDirectory() as td:
        xml_path = Path(td) / "sample1.xml"
        xml_path.write_text(VALID_XML)
        img_w, img_h, objects = parse_voc_xml(xml_path)

    assert (img_w, img_h) == (1000, 500)
    assert len(objects) == 3
    names = [o[0] for o in objects]
    assert names == ["Wrench", "NotAFODClass", "SodaCan"]
    # SodaCan's box should already be clamped to image bounds by parse_voc_xml.
    _, xmin, ymin, xmax, ymax = objects[2]
    assert (xmin, ymin, xmax, ymax) == (0.0, 10.0, 1000.0, 490.0)


def test_convert_directory_end_to_end(tmp_path: Path):
    voc_dir = tmp_path / "voc"
    out_dir = tmp_path / "labels"
    voc_dir.mkdir()

    (voc_dir / "sample1.xml").write_text(VALID_XML)
    (voc_dir / "broken.xml").write_text(MALFORMED_XML)
    (voc_dir / "no_known_objects.xml").write_text(NO_KNOWN_OBJECTS_XML)

    summary = convert_directory(voc_dir, out_dir, CLASS_NAMES)

    assert summary.n_xml_files == 3
    assert summary.n_converted == 1  # only sample1.xml produced a label file
    assert summary.n_skipped_malformed_xml == 1
    assert summary.n_skipped_no_objects == 1  # no_known_objects.xml
    assert summary.n_objects_written == 2  # Wrench + SodaCan from sample1
    assert summary.n_objects_skipped_unknown_class == 2  # one per file
    assert summary.unknown_class_counts["NotAFODClass"] == 2

    # Check the actual written YOLO label file against the hand-computed values.
    out_lines = (out_dir / "sample1.txt").read_text().strip().splitlines()
    assert len(out_lines) == 2

    wrench_line = out_lines[0].split()
    assert wrench_line[0] == "0"  # Wrench is index 0
    assert abs(float(wrench_line[1]) - 0.2) < 1e-6
    assert abs(float(wrench_line[2]) - 0.2) < 1e-6
    assert abs(float(wrench_line[3]) - 0.2) < 1e-6
    assert abs(float(wrench_line[4]) - 0.2) < 1e-6

    sodacan_line = out_lines[1].split()
    assert sodacan_line[0] == "3"  # SodaCan is index 3
    assert abs(float(sodacan_line[1]) - 0.5) < 1e-6
    assert abs(float(sodacan_line[2]) - 0.5) < 1e-6
    assert abs(float(sodacan_line[3]) - 1.0) < 1e-6
    assert abs(float(sodacan_line[4]) - 0.96) < 1e-6

    # broken.xml and no_known_objects.xml must NOT have produced label files.
    assert not (out_dir / "broken.txt").exists()
    assert not (out_dir / "no_known_objects.txt").exists()


def test_list_all_classes_discovers_real_names_without_a_hardcoded_list(tmp_path: Path):
    """This is the check-before-you-guess tool: it must report every class
    name actually present in the raw data, including ones that aren't in
    any predefined list, and it must not crash on the malformed file."""
    voc_dir = tmp_path / "voc"
    voc_dir.mkdir()
    (voc_dir / "sample1.xml").write_text(VALID_XML)
    (voc_dir / "broken.xml").write_text(MALFORMED_XML)

    counts = list_all_classes(voc_dir)

    assert counts["Wrench"] == 1
    assert counts["SodaCan"] == 1
    assert counts["NotAFODClass"] == 1  # discovered even though it's not in any config


def _fastener_xml(class_name: str, w: int = 400, h: int = 400) -> str:
    """A minimal single-object VOC XML for the per-object-folder distribution
    tests below — dimensions match the real dataset's 400x400 format."""
    return f"""<annotation>
  <size><width>{w}</width><height>{h}</height><depth>3</depth></size>
  <object>
    <name>{class_name}</name>
    <bndbox><xmin>10</xmin><ymin>10</ymin><xmax>50</xmax><ymax>50</ymax></bndbox>
  </object>
</annotation>
"""


def test_convert_original_format_distribution_handles_cross_folder_filename_collision(tmp_path: Path):
    """Regression test for the real defect this function exists to avoid
    (found 2026-09-03, run 4): FOD-A's per-object-folder distribution
    restarts frame numbering inside every object folder, so
    "Bolt1/frame/frame_000000.PNG" and "Nut3/frame/frame_000000.PNG" are
    different images that would collide under a filename-stem-only naming
    scheme. Both must survive conversion with distinct, correctly-prefixed
    output names."""
    root = tmp_path / "FullDatasetV.2.1-400x400"

    bolt_dir = root / "Bolt1"
    (bolt_dir / "Annotations").mkdir(parents=True)
    (bolt_dir / "frame").mkdir(parents=True)
    (bolt_dir / "Annotations" / "frame_000000.xml").write_text(_fastener_xml("Bolt"))
    (bolt_dir / "frame" / "frame_000000.PNG").write_bytes(b"BOLT-IMAGE-BYTES")

    nut_dir = root / "Nut3"
    (nut_dir / "Annotations").mkdir(parents=True)
    (nut_dir / "frame").mkdir(parents=True)
    (nut_dir / "Annotations" / "frame_000000.xml").write_text(_fastener_xml("Nut"))
    (nut_dir / "frame" / "frame_000000.PNG").write_bytes(b"NUT-IMAGE-BYTES")

    # A non-object utility folder (no Annotations/ subdir) must be ignored,
    # not crash the walk.
    (root / "All_Dataset_Utility_Files").mkdir(parents=True)
    (root / "All_Dataset_Utility_Files" / "FOD_categorization_annotations.csv").write_text("File,Weather,Light\n")

    out_images = tmp_path / "out" / "images"
    out_labels = tmp_path / "out" / "labels"

    summary = convert_original_format_distribution(root, out_images, out_labels, FASTENER_CLASS_NAMES)

    assert summary.n_xml_files == 2
    assert summary.n_converted == 2
    assert summary.n_skipped_malformed_xml == 0
    assert summary.n_objects_written == 2

    # Distinct, collision-safe names — neither overwrote the other.
    assert (out_labels / "Bolt1__frame_000000.txt").exists()
    assert (out_labels / "Nut3__frame_000000.txt").exists()
    assert (out_images / "Bolt1__frame_000000.PNG").read_bytes() == b"BOLT-IMAGE-BYTES"
    assert (out_images / "Nut3__frame_000000.PNG").read_bytes() == b"NUT-IMAGE-BYTES"

    bolt_line = (out_labels / "Bolt1__frame_000000.txt").read_text().strip().split()
    assert bolt_line[0] == str(FASTENER_CLASS_NAMES.index("Bolt"))
    nut_line = (out_labels / "Nut3__frame_000000.txt").read_text().strip().split()
    assert nut_line[0] == str(FASTENER_CLASS_NAMES.index("Nut"))


def test_convert_original_format_distribution_skips_unknown_class_and_missing_image(tmp_path: Path):
    root = tmp_path / "FullDatasetV.2.1-400x400"

    # In-scope object, but no matching image file in frame/ — must be
    # skipped and reported, not crash.
    missing_img_dir = root / "Washer2"
    (missing_img_dir / "Annotations").mkdir(parents=True)
    (missing_img_dir / "frame").mkdir(parents=True)
    (missing_img_dir / "Annotations" / "frame_000005.xml").write_text(_fastener_xml("Washer"))
    # (no corresponding frame/frame_000005.* written)

    # Object present but not in the configured class list — must be
    # counted, not silently dropped, and must not produce an output pair.
    out_of_scope_dir = root / "Rock1"
    (out_of_scope_dir / "Annotations").mkdir(parents=True)
    (out_of_scope_dir / "frame").mkdir(parents=True)
    (out_of_scope_dir / "Annotations" / "frame_000000.xml").write_text(_fastener_xml("Rock"))
    (out_of_scope_dir / "frame" / "frame_000000.PNG").write_bytes(b"ROCK-IMAGE-BYTES")

    out_images = tmp_path / "out" / "images"
    out_labels = tmp_path / "out" / "labels"

    summary = convert_original_format_distribution(root, out_images, out_labels, FASTENER_CLASS_NAMES)

    assert summary.n_converted == 0
    assert summary.n_skipped_missing_image == 1
    assert summary.n_objects_skipped_unknown_class == 1
    assert summary.unknown_class_counts["Rock"] == 1
    assert not (out_images / "Rock1__frame_000000.PNG").exists()
    assert not (out_labels / "Washer2__frame_000005.txt").exists()
